### ISSUE TITLE
Crash when lldb can't find the requested dpu booting

### ISSUE THREAD

**Issue by amoisson** [upmem/llvm-project#68]
When specifying a DPU to dpu_attach_on_boot, I sometimes get a crash saying:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lldb/dpu_commands.py", line 183, in dpu_attach_on_boot
    while len(dpus_booting) == 0:
TypeError: object of type 'filter' has no len()

I found that the problem seems to be with that line :
https://github.com/upmem/llvm-project/blob/68626c465d72376a4b51109f05ceeca2dcbb2ae0/lldb/scripts/dpu/dpu_commands.py#L189
Which seems to be missing a "list()" like at line 180.
It also seems to hang for a long time if I only do that modification. I am not completely sure whether the line should be moved above the if or not.

**Comment by aharries-upmem** [comment]
I think this whole bit of code is subtly wrong - or at least, makes it very possible for the process to hang.

From what I can understand, it attempts to attach to a specific dpu by listing the DPUs that are "booting", and then checking to see if the specific DPU that we are interested in is in that list. If it isn't, then it keeps querying the list, and re-checking until it is. 

This creates an issue, as this will hang (potentially indefinitely) if the DPU that we're interested in is not (or never) in the "booting" state. In most cases, however, it finds it quickly - which is where your main error (`TypeError: object of type 'filter' has no len()`) comes in - it's the rare case where it isn't found immediately. 

So there are two things to fix: 

- We need to fix the type error, which your `list` call does. This should fix the functionality of "checking until we find the DPU".
- We need to add a timeout to this check, so that if we *continually* fail to find the DPU, we time out after a reasonable length of time (30 seconds or so?)

**Comment by wwolff42** [comment]
fixed in https://github.com/upmem/llvm-project/commit/276cf81852524dc1bd48103067f6a79f944601da
